// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HandleOrder(arg1) {
  return window['go']['handleSpeechApp']['HandleSpeechApp']['HandleOrder'](arg1);
}

export function Startup(arg1) {
  return window['go']['handleSpeechApp']['HandleSpeechApp']['Startup'](arg1);
}

export function UseSparkNaturalDialogue(arg1) {
  return window['go']['handleSpeechApp']['HandleSpeechApp']['UseSparkNaturalDialogue'](arg1);
}
