// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSpeechAPIEventName() {
  return window['go']['systemApp']['SystemApp']['GetSpeechAPIEventName']();
}

export function Startup(arg1) {
  return window['go']['systemApp']['SystemApp']['Startup'](arg1);
}

export function ToggleSpeechAPI() {
  return window['go']['systemApp']['SystemApp']['ToggleSpeechAPI']();
}
